---
title: Stephanie Slattery
timezone: America/Chicago
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/portfolio/:path.html"
  posts:
    title: Posts
    output: true
  talks:
    title: Talks
    output: true
  uploads:
    title: Uploads
    output: true
email: stephanie.n.marx@gmail.com
description: 'Stephanie Slattery is a front end web developer based in Chicago and
  is definitely not made of bees.

'
baseurl: 
url: http://stephanie.slattery.website
twitter_username: sublimemarch
github_username: stephmarx
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
include:
- ".htaccess"
